python weight_analyze.py --model_path /data/xjh/model_weight/llama/llama3.2-1b
python weight_analyze.py --model_path /data/xjh/model_weight/llama/llama3.2-3b
python weight_analyze.py --model_path /data/xjh/model_weight/llama/llama3-8b
python weight_analyze.py --model_path /data/xjh/model_weight/llama/llama2-7b
python weight_analyze.py --model_path /data/xjh/model_weight/llama/llama2-13b
python weight_analyze.py --model_path /data/xjh/model_weight/llama/llama-7b
python weight_analyze.py --model_path /data/xjh/model_weight/llama/llama-13b
python weight_analyze.py --model_path /data/xjh/model_weight/opt/opt-125m
python weight_analyze.py --model_path /data/xjh/model_weight/opt/opt-350m
python weight_analyze.py --model_path /data/xjh/model_weight/opt/opt-1.3b
python weight_analyze.py --model_path /data/xjh/model_weight/opt/opt-2.7b
python weight_analyze.py --model_path /data/xjh/model_weight/opt/opt-6.7b
python weight_analyze.py --model_path /data/xjh/model_weight/opt/opt-13b
